# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcsMetadog < Formula
  desc "CLI tool for searching GCS object which has exact custom-metadata."
  homepage "https://github.com/TlexCypher/gcs-metadog"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Darwin_64bit.tar.gz"
      sha256 "620b99a27e4a8e3525dcddd7410e6ba09b2e5b0707675b518c018ee2a316c9ea"

      def install
        bin.install "gmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Darwin_ARM64.tar.gz"
      sha256 "5ec1a2e9420b975fb43a9489417448803c03bb47e5e7c336171fd34bc47234e7"

      def install
        bin.install "gmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Linux_64bit.tar.gz"
        sha256 "f1337ca7c917bcc907e23cbc3503c6a3fd4b1e9e255bd2be11bd61d563a08726"

        def install
          bin.install "gmd"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Linux_ARM64.tar.gz"
        sha256 "0775eea2b97fc0d5028ec735933070b2395f5418b9d7590f5920c65d8b384ec6"

        def install
          bin.install "gmd"
        end
      end
    end
  end
end
