# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcsMetadog < Formula
  desc "CLI tool for searching GCS object which has exact custom-metadata."
  homepage "https://github.com/TlexCypher/gcs-metadog"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Darwin_64bit.tar.gz"
      sha256 "cad882bd01dbe279496e569fbdc1ede560b7993ca25e33dfe4b563492eefd6f8"

      def install
        bin.install "gmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Darwin_ARM64.tar.gz"
      sha256 "4cf6fd1798a7a2aa17abaffdaa6ab482191605e77495ae9b9510ca1775e425ff"

      def install
        bin.install "gmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Linux_64bit.tar.gz"
        sha256 "22bf0f794aa09692a412a03d07bdfabba351fa83a42a26d83d26a1acefa5186c"

        def install
          bin.install "gmd"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Linux_ARM64.tar.gz"
        sha256 "5c024167138cf097a2a4fa875a3d3f87bdcb5d514857cf4da968d55af15f9e04"

        def install
          bin.install "gmd"
        end
      end
    end
  end
end
