# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmd < Formula
  desc "CLI tool for searching GCS object which has exact custom-metadata."
  homepage "https://github.com/TlexCypher/gcs-metadog"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Darwin_64bit.tar.gz"
      sha256 "c6fd3010bc81ecf1e123d11cbefd0c3e0e15a8378f9d7011ce7c233b37576cf3"

      def install
        bin.install "gmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Darwin_ARM64.tar.gz"
      sha256 "f57dbf02a154571ecc67c8d2bc4d6ee940445cd42c36d0bbc65ab8fd847c9e71"

      def install
        bin.install "gmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Linux_64bit.tar.gz"
        sha256 "3159a3cbcf0da71e077a5a671bfcded1cc8460b215dd2188b31bf05d5e8021e3"

        def install
          bin.install "gmd"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/gcs-metadog/releases/download/v0.0.1/gcs-metadog_0.0.1_Linux_ARM64.tar.gz"
        sha256 "76be841d5892203a6c488bb3acc1b2fd1ec4500bb59250afcdaff2725e8e32dc"

        def install
          bin.install "gmd"
        end
      end
    end
  end
end
