# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxSessionizer < Formula
  desc "Tmux session manager with fzf"
  homepage "https://github.com/tyzerrr/tmux-sessionizer"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tyzerrr/tmux-sessionizer/releases/download/v1.0.1/tmux-sessionizer_Darwin_x86_64.tar.gz"
      sha256 "5d2e2280744654f3acce74bef9e0ad95ab14ca6afd555a3bfac5f473242e469d"

      define_method(:install) do
        bin.install "tmux-sessionizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tyzerrr/tmux-sessionizer/releases/download/v1.0.1/tmux-sessionizer_Darwin_arm64.tar.gz"
      sha256 "0b68a73399f1b9738493e0166ca85e7afb1058b6874e72cba7d412b70c8a7e94"

      define_method(:install) do
        bin.install "tmux-sessionizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyzerrr/tmux-sessionizer/releases/download/v1.0.1/tmux-sessionizer_Linux_x86_64.tar.gz"
      sha256 "393b2b8cdcd460274d257e571981b07f45af120b525377e7f0dcf6655c9af752"
      define_method(:install) do
        bin.install "tmux-sessionizer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tyzerrr/tmux-sessionizer/releases/download/v1.0.1/tmux-sessionizer_Linux_arm64.tar.gz"
      sha256 "4e5c5cee23e64c5068859203d529ad7333d1433529a200c8f19a72ae8c6c258a"
      define_method(:install) do
        bin.install "tmux-sessionizer"
      end
    end
  end

  test do
    system "#{bin}/tmux-sessionizer", "--version"
  end
end
