# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxSessionizer < Formula
  desc "Tmux session manager with fzf"
  homepage "https://github.com/TlexCypher/tmux-sessionizer"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TlexCypher/tmux-sessionizer/releases/download/v0.0.1/tmux-sessionizer_Darwin_x86_64.tar.gz"
      sha256 "63bec657d842a069f824ecfbbfb13480a692c85d030cf63c5c386deb08a3cdaa"

      def install
        bin.install "tmux-sessionizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TlexCypher/tmux-sessionizer/releases/download/v0.0.1/tmux-sessionizer_Darwin_arm64.tar.gz"
      sha256 "279476dd54e6aeb47a8bcd4ded689dd94f007f9c1869aadb2881ac58225e4838"

      def install
        bin.install "tmux-sessionizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/tmux-sessionizer/releases/download/v0.0.1/tmux-sessionizer_Linux_x86_64.tar.gz"
        sha256 "29767c29ff3dfa6bca486d70832cde146748acae0f550128224c53bf447dadd7"

        def install
          bin.install "tmux-sessionizer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/tmux-sessionizer/releases/download/v0.0.1/tmux-sessionizer_Linux_arm64.tar.gz"
        sha256 "daf279334465133ddfd03e0ce8b07b714ece889bfe47b77f528b7421c80e7156"

        def install
          bin.install "tmux-sessionizer"
        end
      end
    end
  end

  test do
    system "#{bin}/tmux-sessionizer", "--version"
  end
end
