# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TmuxSessionizer < Formula
  desc "Tmux session manager with fzf"
  homepage "https://github.com/TlexCypher/tmux-sessionizer"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TlexCypher/tmux-sessionizer/releases/download/v0.0.3/tmux-sessionizer_Darwin_x86_64.tar.gz"
      sha256 "756fabec4ccd37feb4650ca85d072d0a065b0a5bd3008ee12b3661adea207a27"

      def install
        bin.install "tmux-sessionizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TlexCypher/tmux-sessionizer/releases/download/v0.0.3/tmux-sessionizer_Darwin_arm64.tar.gz"
      sha256 "9d7498f7c1f707acb3d308f7d1ec9874c38880bc66cc8a8147acdd173993db26"

      def install
        bin.install "tmux-sessionizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/tmux-sessionizer/releases/download/v0.0.3/tmux-sessionizer_Linux_x86_64.tar.gz"
        sha256 "a24330709c006ee2f5796cd192ddeb29ee1ccacd63ddae5556dbd0e678b29289"

        def install
          bin.install "tmux-sessionizer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/TlexCypher/tmux-sessionizer/releases/download/v0.0.3/tmux-sessionizer_Linux_arm64.tar.gz"
        sha256 "88c349e18555361a713ddf93197dd9ee4d97abbb4e47fff3b2a34c30772eb970"

        def install
          bin.install "tmux-sessionizer"
        end
      end
    end
  end

  test do
    system "#{bin}/tmux-sessionizer", "--version"
  end
end
